// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Kallsonys.PICA.ApiProducts.Product.Models
{
    public partial class Error
    {
        

        /// <summary>
        /// codigo de respuesta
        /// </summary>

        public int? Code { get; set; }

        /// <summary>
        /// Muestra el mensaje corrrespondiente
        /// </summary>
        [Required]
        public string Description { get; set; }
    } // end class

} // end Models namespace

