// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using Kallsonys.PICA.Application.DTO.CommonDTO;

namespace Kallsonys.PICA.Application.DTO.ProductDTO
{
    /// <summary>
    /// Multiple Response Types IdProduct, Error
    /// </summary>
    public partial class MultipleProductPost
    {
        public int IdProduct { get; set; }

        public Error Error { get; set; }
    } // end class
} // end Models namespace