// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using Kallsonys.PICA.Application.DTO.CommonDTO;
using System.Collections.Generic;

namespace Kallsonys.PICA.Application.DTO.ProductDTO
{
    /// <summary>
    /// Multiple Response Types Product, Error
    /// </summary>
    public partial class MultipleProductByCriteriaGet
    {
        public IList<Product> Product { get; set; }

        public Error Error { get; set; }
    } // end class
} // end Models namespace