// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Kallsonys.PICA.Application.DTO.ProductDTO
{
    /// <summary>
    /// Multiple Response Types Product, Error
    /// </summary>
    public partial class MultipleProductIdGet
    {
        


        public Product Product { get; set; }


        public Error Error { get; set; }
    } // end class

} // end Models namespace

