// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using Kallsonys.PICA.Application.DTO.ImageDTO;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Kallsonys.PICA.Application.DTO.ProductDTO
{
    public partial class Product
    {
        [Range(0, int.MaxValue)]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Code { get; set; }

        [Required]
        [Range(0.00, double.MaxValue)]
        public decimal ListPrice { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        [Range(0, int.MaxValue)]
        public int IdCategory { get; set; }

        //[Required]
        public IList<Image> Images { get; set; }

        [Required]
        public int IdProducer { get; set; }

        [Required]
        public int IdProvider { get; set; }

        [Required]
        public bool IsActive { get; set; }
    } // end class
} // end Models namespace