// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Server Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Kallsonys.PICA.ApiProducts.Product.Models
{
    public partial class Product
    {
        

        /// <summary>
        /// Llave primaria
        /// </summary>
        [Required]
        [Range(0,int.MaxValue)]
        public int Id { get; set; }

        /// <summary>
        /// Nombre del producto
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// Codigo del producto
        /// </summary>
        [Required]
        public string Code { get; set; }

        /// <summary>
        /// Descripcion del producto
        /// </summary>

        public string Descripction { get; set; }

        /// <summary>
        /// Id Categoria asociada al producto
        /// </summary>
        [Required]
        public int IdCategory { get; set; }

        /// <summary>
        /// Precio del producto
        /// </summary>
        [Required]
        [Range(0.00,double.MaxValue)]
        public decimal ListPrice { get; set; }

        /// <summary>
        /// Id del fabricante asociado al producto
        /// </summary>
        [Required]
        public int IdProducer { get; set; }

        /// <summary>
        /// URL de la imagen que representa al producto.
        /// </summary>
        [Required]
        public string ImgURL { get; set; }
    } // end class

} // end Models namespace

