// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using Kallsonys.PICA.ApiProducts.Product.Models;

// Do not modify this file. This code was generated by RAML Server Scaffolder

namespace Kallsonys.PICA.ApiProducts.Product
{
    [RoutePrefix("product")]
    public partial class ProductController : ApiController
    {


/// <summary>
		/// Recurso para la creacion de productos - /product
		/// </summary>
		/// <param name="product"></param>
		/// <returns>MultipleProductPost</returns>
        [ResponseType(typeof(MultipleProductPost))]
        [HttpPost]
        [Route("")]
        public virtual async Task<IHttpActionResult> PostBase(Models.Product product)
        {
            // Do not modify this code
                        return await ((IProductController)this).Post(product);
                    }

/// <summary>
		/// Recurso para la consulta de un producto por id - /{id}
		/// </summary>
		/// <param name="id"></param>
		/// <returns>MultipleProductIdGet</returns>
        [ResponseType(typeof(MultipleProductIdGet))]
        [HttpGet]
        [Route("{id}")]
        public virtual async Task<IHttpActionResult> GetBase([FromUri] string id)
        {
            // Do not modify this code
                        return await ((IProductController)this).Get(id);
                    }

/// <summary>
		/// Recurso para la consulta de productos por codigo - /byCode
		/// </summary>
		/// <param name="code"></param>
		/// <returns>MultipleProductByCodeGet</returns>
        [ResponseType(typeof(MultipleProductByCodeGet))]
        [HttpGet]
        [Route("byCode")]
        public virtual async Task<IHttpActionResult> GetByCodeBase([FromUri] string code)
        {
            // Do not modify this code
                        return await ((IProductController)this).GetByCode(code);
                    }

/// <summary>
		/// Recurso para la consulta de productos por nombre o por descripcion - /byCriteria
		/// </summary>
		/// <param name="criteria"></param>
		/// <returns>MultipleProductByCriteriaGet</returns>
        [ResponseType(typeof(MultipleProductByCriteriaGet))]
        [HttpGet]
        [Route("byCriteria")]
        public virtual async Task<IHttpActionResult> GetByCriteriaBase([FromUri] string criteria)
        {
            // Do not modify this code
                        return await ((IProductController)this).GetByCriteria(criteria);
                    }

/// <summary>
		/// Recurso para la consulta del top 5 de productos - /topFive
		/// </summary>
		/// <param name="ids">list of ids</param>
		/// <returns>MultipleProductTopFiveGet</returns>
        [ResponseType(typeof(MultipleProductTopFiveGet))]
        [HttpGet]
        [Route("topFive")]
        public virtual async Task<IHttpActionResult> GetTopFiveBase([FromUri] IList<string> ids)
        {
            // Do not modify this code
                        return await ((IProductController)this).GetTopFive(ids);
                    }
    }
}
