//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kallsonys.PICA.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2CImage
    {
        public int IdImage { get; set; }
        public int IdProduct { get; set; }
        public Nullable<int> IdOffer { get; set; }
        public string Url { get; set; }
        public bool IsThumbnail { get; set; }
        public string Name { get; set; }
    
        public virtual B2COffer B2COffer { get; set; }
        public virtual B2CProduct B2CProduct { get; set; }
    }
}
