//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kallsonys.PICA.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaña
    {
        public int IdCamapaña { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaIncio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Descripcion { get; set; }
        public decimal Descuento { get; set; }
        public int IdProducto { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
